/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_dxutils_jni_JNINativeCRCGenerator */

#ifndef _Included_de_hhu_bsinfo_dxutils_jni_JNINativeCRCGenerator
#define _Included_de_hhu_bsinfo_dxutils_jni_JNINativeCRCGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_dxutils_jni_JNINativeCRCGenerator
 * Method:    hashNative
 * Signature: (IJII)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_dxutils_jni_JNINativeCRCGenerator_hashNative
  (JNIEnv *, jclass, jint, jlong, jint, jint);

/*
 * Class:     de_hhu_bsinfo_dxutils_jni_JNINativeCRCGenerator
 * Method:    hashHeap
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_dxutils_jni_JNINativeCRCGenerator_hashHeap
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
