/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_dxutils_jni_JNIFileRaw */

#ifndef _Included_de_hhu_bsinfo_dxutils_jni_JNIFileRaw
#define _Included_de_hhu_bsinfo_dxutils_jni_JNIFileRaw
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_dxutils_jni_JNIFileRaw
 * Method:    prepareRawDevice
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_dxutils_jni_JNIFileRaw_prepareRawDevice
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     de_hhu_bsinfo_dxutils_jni_JNIFileRaw
 * Method:    open
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_dxutils_jni_JNIFileRaw_open
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     de_hhu_bsinfo_dxutils_jni_JNIFileRaw
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_dxutils_jni_JNIFileRaw_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_hhu_bsinfo_dxutils_jni_JNIFileRaw
 * Method:    delete
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_dxutils_jni_JNIFileRaw_delete
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_hhu_bsinfo_dxutils_jni_JNIFileRaw
 * Method:    write
 * Signature: (IJIIJBB)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_dxutils_jni_JNIFileRaw_write
  (JNIEnv *, jclass, jint, jlong, jint, jint, jlong, jbyte, jbyte);

/*
 * Class:     de_hhu_bsinfo_dxutils_jni_JNIFileRaw
 * Method:    read
 * Signature: (IJIIJ)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_dxutils_jni_JNIFileRaw_read
  (JNIEnv *, jclass, jint, jlong, jint, jint, jlong);

/*
 * Class:     de_hhu_bsinfo_dxutils_jni_JNIFileRaw
 * Method:    length
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_dxutils_jni_JNIFileRaw_length
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_hhu_bsinfo_dxutils_jni_JNIFileRaw
 * Method:    getFileList
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_hhu_bsinfo_dxutils_jni_JNIFileRaw_getFileList
  (JNIEnv *, jclass);

/*
 * Class:     de_hhu_bsinfo_dxutils_jni_JNIFileRaw
 * Method:    printIndexForTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_dxutils_jni_JNIFileRaw_printIndexForTest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
