/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_dxutils_jni_JNIThreadAffinity */

#ifndef _Included_de_hhu_bsinfo_dxutils_jni_JNIThreadAffinity
#define _Included_de_hhu_bsinfo_dxutils_jni_JNIThreadAffinity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_dxutils_jni_JNIThreadAffinity
 * Method:    pinToCore
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_dxutils_jni_JNIThreadAffinity_pinToCore
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_hhu_bsinfo_dxutils_jni_JNIThreadAffinity
 * Method:    pinToCoreSet
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_dxutils_jni_JNIThreadAffinity_pinToCoreSet
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     de_hhu_bsinfo_dxutils_jni_JNIThreadAffinity
 * Method:    moveToRealtimeQueue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_dxutils_jni_JNIThreadAffinity_moveToRealtimeQueue
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
